[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:supervisor

[inet_http_server]
port=:9001

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[supervisord]
identifier=lab
nodaemon=true
pidfile=/var/run/supervisord.pid
logfile=/dev/stdout
loglevel=warning
minfds=2048
minprocs=256

[program-default]
# directory=/data
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true
autostart=false
autorestart=true
startsecs=5
startretries=3
stopwaitsecs=30
killasgroup=true
stopasgroup=true
