[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:supervisor

[inet_http_server]
port=:9001

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[supervisord]
identifier=lab
autostart=False
nodaemon=false
pidfile=/var/run/supervisord.pid
logfile=/dev/stdout
loglevel=warning
logfile_maxbytes=10MB
logfile_backups=10
minfds=2048
minprocs=256

[program-default]
# directory=/data
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autostart=false
autorestart=true
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
redirect_stderr=true
startretries=3

[program:caddy]
command=/usr/local/bin/start-caddy.sh
autostart=true

[program:jupyter]
command=/usr/local/bin/start-jupyterlab.sh
autostart=true
[program:vscode]
command=/usr/local/bin/start-code-server.sh
[program:rserver]
command=/usr/local/bin/start-rserver.sh
[program:shiny]
command=/usr/local/bin/start-shiny-server.sh
